POST http://localhost:3002/auth/register
Content-Type: application/json

{
    "fullName": "Jerry",
    "email": "princewilljeremiah83@gmail.com",
    "password": "rajesh123",
    "role": "admin"
}

###
POST http://localhost:3002/auth/login
Content-Type: application/json

{
    "email": "princewilljeremiah83@gmail.com",
    "password": "rajesh123"
}

###
GET http://localhost:3002/products

###
POST http://localhost:3002/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODdkNDFjNTI4ZTU1YTU0OGE0YzlhMDkiLCJlbWFpbCI6InByaW5jZXdpbGxqZXJlbWlhaDgzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MzAzOTM4OCwiZXhwIjoxNzUzMTI1Nzg4fQ.dJabI6VY2lj5aDk0pLYhER3FmjEMiDoxJ8JGKBKl0Y0

{
    "productName": "Hair pin",
    "cost": 1000,
    "productImages": ["https://res.cloudinary.com/dyrleuyj9/image/upload/v1753040910/images_npyu1w.jpg"],
    "description": "This is a product description"
}

