POST http://localhost:3002/auth/register
Content-Type: application/json

{
    "fullName": "jerry",
    "email": "princewilljeremiah83@gmail.com",
    "password": "987654321",
    "role": "admin"
}

###
POST http://localhost:3002/auth/login
Content-Type: application/json

{
    "email": "princewilljeremiah83@gmail.com",
    "password": "987654321"
}

###
GET http://localhost:3002/products/1/10

###
POST http://localhost:3002/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODk0YTEyNGE3M2QzZDU1ZmJhNjJiZjEiLCJlbWFpbCI6InByaW5jZXdpbGxqZXJlbWlhaDgzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NDU3MTEzNywiZXhwIjoxNzU0NjU3NTM3fQ.x55hxGREovWCf_YCgaoUDvQrqSFXWfZ0uHIW3kiLFQY

{
    "productName": "chinese pin",
    "cost": 3000,
    "productImages": ["https://res.cloudinary.com/dyrleuyj9/image/upload/v1753040910/images_npyu1w.jpg"],
    "description": "This is a product description"
}



